name: Python Automation

on:
  push:
    branches:
      - master

jobs:
  automation:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v3  # Set up Python environment
        with:
          python-version: 3.11  

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Running functional Tests
        run: |
          pytest --alluredir=report_data/ tests/
          allure generate 
          cp ./allure-report/index.html ./
